### PR TITLE
ckan: Update to 1.20.1

### PR DESCRIPTION
**Pull request by QuantumEntangledAndy**

### CODE REVIEW

**Comment by tomyun** [comment]
@BrewTestBot test this please

**Comment by tomyun** [comment]
Probably bot is not listening to my command:)

Seems there was an issue with CI server. You may want to trigger test once again by pushing a amended commit (`git commit --amend` and `git push -f ...`).

**Comment by dunn** [comment]
@tomyun looks like it did work! https://bot.brew.sh/job/Homebrew%20Games%20Pull%20Requests/1031/

But there are some spurious `doctor` errors.

**Comment by QuantumEntangledAndy** [comment]
Is there anything I should do to help this along? From the test it seems that its warning is about `/usr/local/sbin` not being in the path

However I do not believe that is to do with this formula as it is a simple `.exe` download and a mono script to run it?

**Comment by QuantumEntangledAndy** [comment]
Nevermind, I did the `git commit --amend` and `git push -f` you mentioned and the checks seem to have passed now. No idea what that was about. Anyways hope its ok now :).

**Comment by apjanke** [comment]
Looks good now.

Merged. Thank you for your contribution to Homebrew!

**Pull request closed without merging**
