### PR TITLE
fizmo 0.7.10 (new formula)

### PR DESCRIPTION
**Pull request by tomyun**
Updated from #366.

- version bump
- `sdl2` instead of `sdl`

Not sure if the `test` issue still persists with the bot.

### CODE REVIEW

**Comment by mistydemeo** [comment]
Hm, looks like the test still fails.

**Comment by mistydemeo** [comment]
It's also working for me when I test locally.

**Comment by mistydemeo** [comment]
Without being able to reproduce it myself, I'm going to guess the issue is happening here:

```c
  // newterm instead of initscr to init ncurses without clearing screen
  // so we can exit gracefully in case of errors.
  if ((s = newterm(NULL, stdin, stdout)) == NULL)
    return -1;
```

e.g., `newterm()` returns `NULL`, presumably because the way in which the program is being run by the test bot renders it impossible to create a curses session.

**Comment by tomyun** [comment]
Probably since bots are being run headless? Now I'm thinking of keeping `test` for only console version then. Do you think it's acceptable?

**Comment by mistydemeo** [comment]
That's fine, yes! Thank you.

**Comment by tomyun** [comment]
Updated.

**Comment by mistydemeo** [comment]
Thanks!

**Pull request closed without merging**
