### PR TITLE
Pachi 11.00 (new formula)

### PR DESCRIPTION
**Pull request by apetresc**
Pachi is one of the strongest open-source Go engines available. It also integrates very well with existing homebrew-games formulas like `go-gui` and `gnugo`.

Passes `brew audit --new-formula`.

### CODE REVIEW

**Comment by tomyun** [comment]
Build failed on [Mavericks](https://bot.brew.sh/job/Homebrew%20Games%20Pull%20Requests/993/):

```
==> make
[CC]   board.c
[CC]   gtp.c
[CC]   move.c
[MAKE all]   random
[CC]   random.c
clang: error: unknown argument: '-frename-registers'
clang: error: unknown argument: '-frename-registers'
make: *** [move.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [board.o] Error 1
clang: error: unknown argument: '-frename-registers'
make: *** [gtp.o] Error 1
clang: error: unknown argument: '-frename-registers'
make[1]: *** [random.o] Error 1
make: *** [all-recursive] Error 1
```

It might be due to outdated C++11 support from `clang` in Mavericks. Do you know of any upstream issues on that?

**Comment by apjanke** [comment]
There's no upstream fixes for older OSes coming.

You could try simply doing a `fails_with :clang` to get it to build with gcc here, possibly conditioning that on the OS version.

You might consider making `patterns` and `book` enabled by default, so users installing from bottles get them.

The fact that you have to set the working directory to take advantage of the downloaded files is pretty lame. That sounds worthy of an upstream bug report.

**Comment by apetresc** [comment]
Thanks for taking a look, all :)

> There's no upstream fixes for older OSes coming.
I agree with that assessment. I'll modify the formula to fall back to `gcc` on Mavericks and lower.

> You might consider making patterns and book enabled by default, so users installing from bottles get them.
Okay, cool. Will do.

> The fact that you have to set the working directory to take advantage of the downloaded files is pretty lame. That sounds worthy of an upstream bug report.
Agreed. In fact, I already have a fix for it in a series of upstream patches I'm preparing, but they might take a bit of time to make it in, so I'll just update the formula when it happens.

**Comment by apetresc** [comment]
The proposed changes have all been made :)

**Comment by apjanke** [comment]
And the test bot is happy. Merged. Thank you for your contribution to Homebrew!

**Comment by tomyun** [comment]
Oh, I was about to make some questions/suggestions for this formula, but maybe it's a bit late. I'll list them anyways:

1. Is there any specific reason to use `share`(`#{prefix}/share`) instead of `pkgshare`(`#{prefix}/share/pachi`)? The latter will be preferred in most cases.
2. You may want to consider having executable colocated with the data path and instead writing a script for running it. `write_exec_script` comes handy in this case: #511, #616, #369.
3. A single squashed commit is preferred for pull. You could try `git rebase -i` and `git push -f`.

**Comment by apjanke** [comment]
It's merged now, but those suggestions would make a good separate PR.

1. Pointing in to `opt` to avoid a specific version dependency may be even better.

**Comment by apetresc** [comment]
@tomyun: Those are great suggestions. I will file those separately later tonight.

As for the squashing, I figured that wasn't needed anymore now that GitHub's merge button has that handy squash option, but I guess you guys don't actually use the button, so I'll make sure to pre-squash next time :)

**Comment by apjanke** [comment]
I squashed the commits myself when merging them this time. (We use a merge tool that allows this.) We do appreciate it if they're already squashed in the PR; saves a bit of work and makes reading the PR easier!

**Pull request closed without merging**
