### PR TITLE
solarus 1.5.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by dunn** [comment]
A new Qt5 dep? http://bot.brew.sh/job/Homebrew%20Games%20Pull%20Requests/910/version=yosemite/testReport/junit/brew-test-bot/yosemite/install_homebrew_games_solarus/

**Comment by ilovezfs** [comment]
Yup, and then the build fails with a bunch of errors :(
```
[ 92%] Building CXX object gui/CMakeFiles/solarus_gui_lib.dir/src/about_dialog.cpp.o
cd /tmp/solarus-20160730-3213-1n0jrgm/solarus-1.5.0/build/gui && /usr/bin/clang++   -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DSOLARUS_DEFAULT_QUEST=\".\" -DSOLARUS_DEFAULT_QUEST_HEIGHT=240 -DSOLARUS_DEFAULT_QUEST_WIDTH=320 -DSOLARUS_WRITE_DIR=\"Solarus\" -Dsolarus_gui_lib_EXPORTS -I/tmp/solarus-20160730-3213-1n0jrgm/solarus-1.5.0/build/gui -I/tmp/solarus-20160730-3213-1n0jrgm/solarus-1.5.0/gui -I/tmp/solarus-20160730-3213-1n0jrgm/solarus-1.5.0/build/include -I/tmp/solarus-20160730-3213-1n0jrgm/solarus-1.5.0/include -I/tmp/solarus-20160730-3213-1n0jrgm/solarus-1.5.0/include/solarus/third_party -I/tmp/solarus-20160730-3213-1n0jrgm/solarus-1.5.0/include/solarus/third_party/snes_spc -isystem /usr/local/include/libmodplug -isystem /usr/local/include/SDL2 -isystem /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/OpenAL.framework/Headers -isystem /usr/local/include/vorbis -isystem /usr/local/include/ogg -isystem /usr/local/include/luajit-2.0 -isystem /usr/local/include -I/tmp/solarus-20160730-3213-1n0jrgm/solarus-1.5.0/gui/include -iframework /usr/local/opt/qt5/lib -isystem /usr/local/opt/qt5/lib/QtWidgets.framework/Headers -isystem /usr/local/opt/qt5/lib/QtGui.framework/Headers -isystem /System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -isystem /usr/local/opt/qt5/lib/QtCore.framework/Headers -isystem /usr/local/opt/qt5/./mkspecs/macx-clang  -std=c++11 -stdlib=libc++  -Wno-error -Wall -Wextra -Wno-unknown-pragmas -Wno-fatal-errors -DNDEBUG -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.7 -fPIC   -fPIC -o CMakeFiles/solarus_gui_lib.dir/src/about_dialog.cpp.o -c /tmp/solarus-20160730-3213-1n0jrgm/solarus-1.5.0/gui/src/about_dialog.cpp
In file included from /tmp/solarus-20160730-3213-1n0jrgm/solarus-1.5.0/gui/src/about_dialog.cpp:17:
In file included from /tmp/solarus-20160730-3213-1n0jrgm/solarus-1.5.0/gui/include/solarus/gui/about_dialog.h:21:
In file included from /usr/local/opt/qt5/lib/QtWidgets.framework/Headers/QDialog:1:
In file included from /usr/local/opt/qt5/lib/QtWidgets.framework/Headers/qdialog.h:37:
In file included from /usr/local/opt/qt5/lib/QtWidgets.framework/Headers/qwidget.h:45:
/usr/local/opt/qt5/lib/QtWidgets.framework/Headers/qsizepolicy.h:45:1: error: unknown type name
      'Q_DECL_CONST_FUNCTION'
Q_DECL_CONST_FUNCTION inline uint qHash(QSizePolicy key, uint seed = 0) Q_DECL_NOTHROW;
^
/usr/local/opt/qt5/lib/QtWidgets.framework/Headers/qsizepolicy.h:45:23: error: expected
      unqualified-id
Q_DECL_CONST_FUNCTION inline uint qHash(QSizePolicy key, uint seed = 0) Q_DECL_NOTHROW;
                      ^
/usr/local/opt/qt5/lib/QtWidgets.framework/Headers/qsizepolicy.h:49:5: error: expected expression
    Q_GADGET
    ^
/usr/local/include/QtCore/qobjectdefs.h:173:18: note: expanded from macro 'Q_GADGET'
#define Q_GADGET \
                 ^
In file included from /tmp/solarus-20160730-3213-1n0jrgm/solarus-1.5.0/gui/src/about_dialog.cpp:17:
In file included from /tmp/solarus-20160730-3213-1n0jrgm/solarus-1.5.0/gui/include/solarus/gui/about_dialog.h:21:
In file included from /usr/local/opt/qt5/lib/QtWidgets.framework/Headers/QDialog:1:
In file included from /usr/local/opt/qt5/lib/QtWidgets.framework/Headers/qdialog.h:37:
In file included from /usr/local/opt/qt5/lib/QtWidgets.framework/Headers/qwidget.h:45:
/usr/local/opt/qt5/lib/QtWidgets.framework/Headers/qsizepolicy.h:47:24: error: variable has
      incomplete type 'class Q_WIDGETS_EXPORT'
class Q_WIDGETS_EXPORT QSizePolicy
                       ^
/usr/local/opt/qt5/lib/QtWidgets.framework/Headers/qsizepolicy.h:47:7: note: forward declaration of
      'Q_WIDGETS_EXPORT'
class Q_WIDGETS_EXPORT QSizePolicy
      ^
/usr/local/opt/qt5/lib/QtWidgets.framework/Headers/qsizepolicy.h:161:31: error: incomplete type
      'QSizePolicy' named in nested name specifier
Q_DECLARE_OPERATORS_FOR_FLAGS(QSizePolicy::ControlTypes)
                              ^~~~~~~~~~~~~
/usr/local/include/QtCore/qglobal.h:2471:32: note: expanded from macro
      'Q_DECLARE_OPERATORS_FOR_FLAGS'
Q_DECL_CONSTEXPR inline QFlags<Flags::enum_type> operator|(Flags::enum_type f1, Flags::enum_t...
                               ^~~~~
/usr/local/opt/qt5/lib/QtWidgets.framework/Headers/qsizepolicy.h:43:7: note: forward declaration of
      'QSizePolicy'
class QSizePolicy;
      ^
/usr/local/opt/qt5/lib/QtWidgets.framework/Headers/qsizepolicy.h:161:31: error: incomplete type
      'QSizePolicy' named in nested name specifier
Q_DECLARE_OPERATORS_FOR_FLAGS(QSizePolicy::ControlTypes)
                              ^~~~~~~~~~~~~
/usr/local/include/QtCore/qglobal.h:2471:60: note: expanded from macro
      'Q_DECLARE_OPERATORS_FOR_FLAGS'
Q_DECL_CONSTEXPR inline QFlags<Flags::enum_type> operator|(Flags::enum_type f1, Flags::enum_t...
                                                           ^~~~~
/usr/local/opt/qt5/lib/QtWidgets.framework/Headers/qsizepolicy.h:43:7: note: forward declaration of
      'QSizePolicy'
class QSizePolicy;
      ^
/usr/local/opt/qt5/lib/QtWidgets.framework/Headers/qsizepolicy.h:161:31: error: incomplete type
      'QSizePolicy' named in nested name specifier
Q_DECLARE_OPERATORS_FOR_FLAGS(QSizePolicy::ControlTypes)
                              ^~~~~~~~~~~~~
/usr/local/include/QtCore/qglobal.h:2471:81: note: expanded from macro
      'Q_DECLARE_OPERATORS_FOR_FLAGS'
Q_DECL_CONSTEXPR inline QFlags<Flags::enum_type> operator|(Flags::enum_type f1, Flags::enum_t...
                                                                                ^~~~~
/usr/local/opt/qt5/lib/QtWidgets.framework/Headers/qsizepolicy.h:43:7: note: forward declaration of
      'QSizePolicy'
class QSizePolicy;
      ^
/usr/local/opt/qt5/lib/QtWidgets.framework/Headers/qsizepolicy.h:161:31: error: incomplete type
      'QSizePolicy' named in nested name specifier
Q_DECLARE_OPERATORS_FOR_FLAGS(QSizePolicy::ControlTypes)
                              ^~~~~~~~~~~~~
/usr/local/include/QtCore/qglobal.h:2472:17: note: expanded from macro
      'Q_DECLARE_OPERATORS_FOR_FLAGS'
{ return QFlags<Flags::enum_type>(f1) | f2; } \
                ^~~~~
/usr/local/opt/qt5/lib/QtWidgets.framework/Headers/qsizepolicy.h:43:7: note: forward declaration of
      'QSizePolicy'
class QSizePolicy;
      ^
/usr/local/opt/qt5/lib/QtWidgets.framework/Headers/qsizepolicy.h:161:31: error: incomplete type
      'QSizePolicy' named in nested name specifier
Q_DECLARE_OPERATORS_FOR_FLAGS(QSizePolicy::ControlTypes)
                              ^~~~~~~~~~~~~
/usr/local/include/QtCore/qglobal.h:2473:32: note: expanded from macro
      'Q_DECLARE_OPERATORS_FOR_FLAGS'
Q_DECL_CONSTEXPR inline QFlags<Flags::enum_type> operator|(Flags::enum_type f1, QFlags<Flags:...
                               ^~~~~
/usr/local/opt/qt5/lib/QtWidgets.framework/Headers/qsizepolicy.h:43:7: note: forward declaration of
      'QSizePolicy'
class QSizePolicy;
      ^
/usr/local/opt/qt5/lib/QtWidgets.framework/Headers/qsizepolicy.h:161:31: error: incomplete type
      'QSizePolicy' named in nested name specifier
Q_DECLARE_OPERATORS_FOR_FLAGS(QSizePolicy::ControlTypes)
                              ^~~~~~~~~~~~~
/usr/local/include/QtCore/qglobal.h:2473:60: note: expanded from macro
      'Q_DECLARE_OPERATORS_FOR_FLAGS'
Q_DECL_CONSTEXPR inline QFlags<Flags::enum_type> operator|(Flags::enum_type f1, QFlags<Flags:...
                                                           ^~~~~
/usr/local/opt/qt5/lib/QtWidgets.framework/Headers/qsizepolicy.h:43:7: note: forward declaration of
      'QSizePolicy'
class QSizePolicy;
      ^
/usr/local/opt/qt5/lib/QtWidgets.framework/Headers/qsizepolicy.h:161:31: error: incomplete type
      'QSizePolicy' named in nested name specifier
Q_DECLARE_OPERATORS_FOR_FLAGS(QSizePolicy::ControlTypes)
                              ^~~~~~~~~~~~~
/usr/local/include/QtCore/qglobal.h:2473:88: note: expanded from macro
      'Q_DECLARE_OPERATORS_FOR_FLAGS'
  ...inline QFlags<Flags::enum_type> operator|(Flags::enum_type f1, QFlags<Flags::enum_type> f2) \
                                                                           ^~~~~
/usr/local/opt/qt5/lib/QtWidgets.framework/Headers/qsizepolicy.h:43:7: note: forward declaration of
      'QSizePolicy'
class QSizePolicy;
      ^
/usr/local/opt/qt5/lib/QtWidgets.framework/Headers/qsizepolicy.h:161:31: error: incomplete type
      'QSizePolicy' named in nested name specifier
Q_DECLARE_OPERATORS_FOR_FLAGS(QSizePolicy::ControlTypes)
                              ^~~~~~~~~~~~~
/usr/local/include/QtCore/qglobal.h:2474:50: note: expanded from macro
      'Q_DECLARE_OPERATORS_FOR_FLAGS'
{ return f2 | f1; } Q_DECLARE_INCOMPATIBLE_FLAGS(Flags)
                                                 ^~~~~
/usr/local/include/QtCore/qglobal.h:2467:36: note: expanded from macro 'Q_DECLARE_INCOMPATIBLE_FLAGS'
inline QIncompatibleFlag operator|(Flags::enum_type f1, int f2) \
                                   ^~~~~
/usr/local/opt/qt5/lib/QtWidgets.framework/Headers/qsizepolicy.h:43:7: note: forward declaration of
      'QSizePolicy'
class QSizePolicy;
      ^
/usr/local/opt/qt5/lib/QtWidgets.framework/Headers/qsizepolicy.h:164:18: error: variable has
      incomplete type 'Q_WIDGETS_EXPORT'
Q_WIDGETS_EXPORT QDataStream &operator<<(QDataStream &, const QSizePolicy &);
                 ^
/usr/local/opt/qt5/lib/QtWidgets.framework/Headers/qsizepolicy.h:47:7: note: forward declaration of
      'Q_WIDGETS_EXPORT'
class Q_WIDGETS_EXPORT QSizePolicy
      ^
/usr/local/opt/qt5/lib/QtWidgets.framework/Headers/qsizepolicy.h:164:29: error: expected ';' after
      top level declarator
Q_WIDGETS_EXPORT QDataStream &operator<<(QDataStream &, const QSizePolicy &);
                            ^
/usr/local/opt/qt5/lib/QtWidgets.framework/Headers/qsizepolicy.h:165:18: error: variable has
      incomplete type 'Q_WIDGETS_EXPORT'
Q_WIDGETS_EXPORT QDataStream &operator>>(QDataStream &, QSizePolicy &);
                 ^
/usr/local/opt/qt5/lib/QtWidgets.framework/Headers/qsizepolicy.h:47:7: note: forward declaration of
      'Q_WIDGETS_EXPORT'
class Q_WIDGETS_EXPORT QSizePolicy
      ^
/usr/local/opt/qt5/lib/QtWidgets.framework/Headers/qsizepolicy.h:165:29: error: expected ';' after
      top level declarator
Q_WIDGETS_EXPORT QDataStream &operator>>(QDataStream &, QSizePolicy &);
                            ^
/usr/local/opt/qt5/lib/QtWidgets.framework/Headers/qsizepolicy.h:169:18: error: variable has
      incomplete type 'Q_WIDGETS_EXPORT'
Q_WIDGETS_EXPORT QDebug operator<<(QDebug dbg, const QSizePolicy &);
                 ^
/usr/local/opt/qt5/lib/QtWidgets.framework/Headers/qsizepolicy.h:47:7: note: forward declaration of
      'Q_WIDGETS_EXPORT'
class Q_WIDGETS_EXPORT QSizePolicy
      ^
/usr/local/opt/qt5/lib/QtWidgets.framework/Headers/qsizepolicy.h:169:24: error: expected ';' after
      top level declarator
Q_WIDGETS_EXPORT QDebug operator<<(QDebug dbg, const QSizePolicy &);
                       ^
/usr/local/opt/qt5/lib/QtWidgets.framework/Headers/qsizepolicy.h:172:13: error: incomplete type
      'QSizePolicy' named in nested name specifier
inline void QSizePolicy::transpose() {
            ^~~~~~~~~~~~~
/usr/local/opt/qt5/lib/QtWidgets.framework/Headers/qsizepolicy.h:43:7: note: forward declaration of
      'QSizePolicy'
class QSizePolicy;
      ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[2]: *** [gui/CMakeFiles/solarus_gui_lib.dir/src/about_dialog.cpp.o] Error 1
make[1]: *** [gui/CMakeFiles/solarus_gui_lib.dir/all] Error 2
make: *** [all] Error 2
bash-3.2$ 
```

**Comment by tomyun** [comment]
You'd like to add `"-DSOLARUS_GUI=OFF"` option to prevent cmake from building the new Qt-based GUI. Otherwise we may need to fiddle with Xcode project file to properly build GUI, I guess.

**Comment by apjanke** [comment]
Thanks @tomyun! That fixed the build. Also had to adjust the test because the command name changed. Opened a new PR #657 with the updates.

**Comment by apjanke** [comment]
Superseded by #657

**Pull request closed without merging**
