### PR TITLE
ppsspp: revision for glew

### PR DESCRIPTION
**Pull request by tomyun**
The bottle has been broken since Homebrew/homebrew-core#3269.

### CODE REVIEW

**Comment by tomyun** [comment]
Is there any reason these revision PRs are not being merged for some time?

**Comment by dunn** [comment]
No, it's just that the games tap doesn't get much attention, I'm afraid.

**Comment by dunn** [comment]
@BrewTestBot test this please

**Comment by dunn** [comment]
Merged as a38d5d9d8d5d96d2be8154b4c491073e03e71cec, sorry for the delay.

**Comment by tomyun** [comment]
Thanks for handling this. It'd be nice to see other similar revisions for `glew` (#630, #631) and `sdl_gfx` (#632, #635, #636) get merged soon.

**Comment by dunn** [comment]
I'll start rebuilding those.

I've also invited you to be a collaborator on this repository, since you've been doing a lot of work here and we haven't been as responsive as we should.

**Comment by dunn** [comment]
Here are some docs that might be useful:
- https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Maintainer-Guidelines.md
- https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Brew-Test-Bot-For-Core-Contributors.md

**Comment by tomyun** [comment]
Thanks for your invitation. It's my pleasure to have more means to contribute to this repository. By the way, can I merge my own PRs to master? It sounds exciting, but also quite risky.

**Comment by dunn** [comment]
Yes!  But feel free to ask another maintainer to give a 👍 if you'd like.

**Comment by tomyun** [comment]
Sounds good to me. Thanks!

**Comment by dunn** [comment]
And if you make an account on bintray.com you should be able to create an API key and publish bottles with `brew pull --bottle`

**Pull request closed without merging**
