### PR TITLE
Update dwarf-fortress to version 0.42.05

### PR DESCRIPTION
**Pull request by BlueChili**
Updated to latest release.

### CODE REVIEW

**Comment by dunn** [comment]
@BrewTestBot test this please

**Comment by dunn** [comment]
Sorry, could you rebase this against the master branch?

**Comment by BlueChili** [comment]
@dunn master is already at 0.43.01 maybe close this PR?

**Comment by dunn** [comment]
Oh, woops! I guess someone else opened a PR and we overlooked this one.  Thanks anyway for the submission!

**Pull request closed without merging**
