### PR TITLE
corsixth 0.60 (new formula)

### PR DESCRIPTION
**Pull request by tomyun**
A formula I tested a while ago, then somehow lost in memories. It at least worked on my machine with demo game files. There is no `test` as usual for bundle apps.

### CODE REVIEW

**Comment by apjanke** [comment]
@BrewTestBot test this please

**Comment by apjanke** [comment]
Looks good.

Merged. Thank you for your contribution to Homebrew!

**Comment by TheCycoONE** [comment]
@tomyun is there a way we can reach you to coordinate future releases @CorsixTH?

**Comment by tomyun** [comment]
@TheCycoONE you may open an issue here at homebrew-games tap to let us know when new releases coming close and we can get ready to update the formula.

**Pull request closed without merging**
