### PR TITLE
rom-tools 0.162

### PR DESCRIPTION
**Pull request by mbcoguno**
`desc` DSL isn't ready yet.

### CODE REVIEW

**Comment by mbcoguno** [comment]
As MAME's homepage says:

> MESS is now integral part of MAME and will be distributed as such.
> As of 0.162 the MAME and MESS projects have been combined into a single emulator.

Although mame and mess still has its own source subfolder (and manfile), the build target is combined into single one, that is, they have the same execution filename `mame`. We need to decide how `mess` and

**Comment by mbcoguno** [comment]
As MAME's homepage says:

> MESS is now integral part of MAME and will be distributed as such.
> As of 0.162 the MAME and MESS projects have been combined into a single emulator.

Although `mame` and `mess` still has its own source subfolder (and manfile), the build target is combined into single one, that is, they have the same execution filename `mame`. We need to decide how `mess` and `ume` formulae should be do.

1. Add `conflict_with` DSL each other.
2. Rename `mame64` to `mame`/`mess`/`ume` in their formulae with previous subtarget.
3. Build `mame` with default target (like previous `ume`) and simply delete `mess` and `ume` formulae.
4. Build `mame` with default target (like previous `ume`) and boneyard `mess` and `ume`.

BTW, I prefer 3.

Any suggestion?

**Comment by mistydemeo** [comment]
3 is my preference as well.

**Comment by mistydemeo** [comment]
Thanks very much, merged!

**Pull request closed without merging**
