### PR TITLE
qtads 2.1.7

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by dunn** [comment]
New dep! `Project ERROR: Package SDL2_mixer not found`

**Comment by tomyun** [comment]
You may also want to use `qt5` and `sdl2` instead of legacy.

**Comment by apjanke** [comment]
Still borked when adding `sdl2_mixer`.

```
src/qtadssound.cc:24:10: fatal error: 'SDL_sound.h' file not found
#include <SDL_sound.h>
         ^
1 error generated.
make: *** [obj/qtadssound.o] Error 1
make: *** Waiting for unfinished jobs....
```

Compilation fails under `qt5`, too.

Mind if we just close this out until someone wants to tackle the compilation issues?

**Comment by ilovezfs** [comment]
fixed

**Comment by ilovezfs** [comment]
@DomT4 didn't you tell @zmwangx the other day that max os requirement filters down automatically? Apparently not ...

**Comment by DomT4** [comment]
Sorry, I gave you a rather oversimplified answer at the time because the situation is a bit of a mess. For _users_ it does mostly trickle down automatically, unless they have _(for example)_ a preexisting `qt` installation, in which case it works, but otherwise:
```
~> brew install -v shiboken
qt: This formula either does not compile or function as expected on macOS
versions newer than El Capitan due to an upstream incompatibility.
Error: An unsatisfied requirement failed this build.
```

However the CI tries to be more deliberate than a user, so you encounter repeated failures where most humans will only see the one.

**Comment by MikeMcQuaid** [comment]
@ilovezfs Could you Qt5ify this?

**Comment by MikeMcQuaid** [comment]
@ilovezfs Or alternatively just ☠️

**Comment by ilovezfs** [comment]
@MikeMcQuaid Qt5'ified.

**Comment by MikeMcQuaid** [comment]
@ilovezfs great work.

**Pull request closed without merging**
