### PR TITLE
advancemenu 3.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by mistydemeo** [comment]
@BrewTestBot test this please

**Comment by mistydemeo** [comment]
Looks like it's failing on Yosemite.

**Comment by mistydemeo** [comment]
Looks like advancemame and advancemenu are installing the same files in the 3.0 bump.

**Comment by ilovezfs** [comment]
Hmm odd then that one would fail to build and the other, not.

**Comment by mistydemeo** [comment]
Yeah, I don't really get it. ¯\_(ツ)_/¯

**Pull request closed without merging**
