### PR TITLE
easyrpg-player 0.5.0

### PR DESCRIPTION
**Pull request by tomyun**
- version bump
- `boost` no longer used
- bunch of new deps, mostly for audio
- updated `homepage`

#667 is required to get this merged.

### CODE REVIEW

**Comment by apjanke** [comment]
Build [failure](https://bot.brew.sh/job/Homebrew%20Games%20Pull%20Requests/1030/), I'm afraid.

```
libtool: compile:  clang++ -DHAVE_CONFIG_H -I. -I./src -std=c++11 -I/usr/local/Cellar/icu4c/57.1/include -I/usr/local/Cellar/expat/2.2.0/include -I/usr/local/Cellar/liblcf/0.4.1_1/include/liblcf -I/usr/local/Cellar/pixman/0.34.0/include/pixman-1 -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/Cellar/pcre/8.39/include -I/usr/local/Cellar/glib/2.48.2/include/glib-2.0 -I/usr/local/Cellar/glib/2.48.2/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/harfbuzz/1.3.0/include/harfbuzz -D_THREAD_SAFE -I/usr/local/include/SDL2 -D_THREAD_SAFE -I/usr/local/include/SDL2 -I/usr/local/Cellar/libpng/1.6.25/include/libpng16 -I/usr/local/Cellar/mpg123/1.23.6/include -I/usr/local/Cellar/libogg/1.3.2/include -I/usr/local/Cellar/libvorbis/1.3.5/include -I/usr/local/Cellar/libsndfile/1.0.26/include -I/usr/local/Cellar/libxmp/4.4.0/include -I/usr/local/Cellar/speex/1.2rc1/include -g -O2 -c src/game_actors.cpp -o src/libeasyrpg_player_la-game_actors.o
libtool: compile:  clang++ -DHAVE_CONFIG_H -I. -I./src -std=c++11 -I/usr/local/Cellar/icu4c/57.1/include -I/usr/local/Cellar/expat/2.2.0/include -I/usr/local/Cellar/liblcf/0.4.1_1/include/liblcf -I/usr/local/Cellar/pixman/0.34.0/include/pixman-1 -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/Cellar/pcre/8.39/include -I/usr/local/Cellar/glib/2.48.2/include/glib-2.0 -I/usr/local/Cellar/glib/2.48.2/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/harfbuzz/1.3.0/include/harfbuzz -D_THREAD_SAFE -I/usr/local/include/SDL2 -D_THREAD_SAFE -I/usr/local/include/SDL2 -I/usr/local/Cellar/libpng/1.6.25/include/libpng16 -I/usr/local/Cellar/mpg123/1.23.6/include -I/usr/local/Cellar/libogg/1.3.2/include -I/usr/local/Cellar/libvorbis/1.3.5/include -I/usr/local/Cellar/libsndfile/1.0.26/include -I/usr/local/Cellar/libxmp/4.4.0/include -I/usr/local/Cellar/speex/1.2rc1/include -g -O2 -c src/game_battle.cpp -o src/libeasyrpg_player_la-game_battle.o
src/game_actor.cpp:663:19: error: no member named 'super_guard' in 'RPG::SaveActor'
        return GetData().super_guard;
               ~~~~~~~~~ ^
src/game_actor.cpp:909:13: error: no member named 'battler_animation' in 'RPG::SaveActor'
                GetData().battler_animation = GetClass()->battler_animation;
                ~~~~~~~~~ ^
src/game_actor.cpp:909:45: error: no member named 'battler_animation' in 'RPG::Class'
                GetData().battler_animation = GetClass()->battler_animation;
                                              ~~~~~~~~~~  ^
src/game_actor.cpp:910:13: error: no member named 'super_guard' in 'RPG::SaveActor'
                GetData().super_guard = GetClass()->super_guard;
                ~~~~~~~~~ ^
src/game_actor.cpp:911:42: error: no member named 'lock_equipment' in 'RPG::Class'; did you mean 'fix_equipment'?
                GetData().lock_equipment = GetClass()->lock_equipment;
                                                       ^~~~~~~~~~~~~~
                                                       fix_equipment
/usr/local/Cellar/liblcf/0.4.1_1/include/liblcf/rpg_class.h:28:8: note: 'fix_equipment' declared here
                bool fix_equipment = false;
                     ^
src/game_actor.cpp:912:38: error: no member named 'two_weapon' in 'RPG::Class'
                GetData().two_weapon = GetClass()->two_weapon;
                                       ~~~~~~~~~~  ^
src/game_actor.cpp:917:13: error: no member named 'super_guard' in 'RPG::SaveActor'
                GetData().super_guard = actor.super_guard;
                ~~~~~~~~~ ^
src/game_actor.cpp:918:36: error: no member named 'lock_equipment' in 'RPG::Actor'; did you mean 'fix_equipment'?
                GetData().lock_equipment = actor.lock_equipment;
                                                 ^~~~~~~~~~~~~~
                                                 fix_equipment
/usr/local/Cellar/liblcf/0.4.1_1/include/liblcf/rpg_actor.h:41:8: note: 'fix_equipment' declared here
                bool fix_equipment = false;
                     ^
src/game_actor.cpp:919:32: error: no member named 'two_weapon' in 'RPG::Actor'
                GetData().two_weapon = actor.two_weapon;
                                       ~~~~~ ^
src/game_actor.cpp:922:13: error: no member named 'battler_animation' in 'RPG::SaveActor'
                GetData().battler_animation = 0;
                ~~~~~~~~~ ^
src/game_actor.cpp:1008:16: error: no member named 'battler_animation' in 'RPG::SaveActor'
        if (GetData().battler_animation <= 0) {
            ~~~~~~~~~ ^
src/game_actor.cpp:1014:23: error: no member named 'battler_animation' in 'RPG::Class'
                        anim = GetClass()->battler_animation;
                               ~~~~~~~~~~  ^
src/game_actor.cpp:1019:20: error: no member named 'battler_animation' in 'RPG::SaveActor'
                anim = GetData().battler_animation;
                       ~~~~~~~~~ ^
13 errors generated.
make: *** [src/libeasyrpg_player_la-game_actor.lo] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by tomyun** [comment]
It requires `liblcf` 0.5.0. As #667 got just merged, it should build now. Let me call the bot to rebuild this.

**Comment by tomyun** [comment]
@BrewTestBot test this please

**Comment by apjanke** [comment]
That worked.

Merged! Thank you for your contribution to Homebrew.

**Pull request closed without merging**
