### PR TITLE
scummvm-tools 1.8.0 (new formula)

### PR DESCRIPTION
**Pull request by tomyun**
A collection of [tools](http://wiki.scummvm.org/index.php/User_Manual/Appendix:_Tools) for ScummVM.

### CODE REVIEW

**Comment by dunn** [comment]
Would it make sense for this to be included in the ScummVM formula?

**Comment by tomyun** [comment]
Maybe we'd better have a separate formula since they have different source archive and dependencies.

**Comment by tomyun** [comment]
By the way, `scummvm-tools` have own release schedule than main `scummvm`. It seems to be much sporadic.

**Comment by dunn** [comment]
@brewtestbot test this please

**Comment by dunn** [comment]
Merged as d7426298d0017519a365cb310658d166069d255d, thanks!

**Pull request closed without merging**
