### PR TITLE
nethack: Add a recipe for a fork of 3.6.0 with GUIs

### PR DESCRIPTION
**Pull request by mikeage**
This fork offers graphical interfaces (both SDL2 and Qt4) for MacOS X.

### CODE REVIEW

**Comment by mikeage** [comment]
This recipe works, but I'm pretty sure there's a lot of room for improvement in the naming. Suggestions welcome. 

Note that the official code for 3.6.0 does not support tiled interfaces on Mac OS, so there's no way to implement this in the main version.

**Comment by RikerW** [comment]
@mikeage it apparently failed the checks?

**Comment by mikeage** [comment]
Correct... it's nowhere near popular enough.

**Comment by RikerW** [comment]
Is that what the check looks for?  And it should be added anyway IMO.

**Comment by mikeage** [comment]
Yes. It'd be nice, but the official policy is pretty clear :-/

**Comment by apjanke** [comment]
Yeah, this is not popular enough to live in one of the official Homebrew taps. This is a good candidate for [your own tap](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/How-to-Create-and-Maintain-a-Tap.md), or maybe a community tap for NetHack variants.

**Pull request closed without merging**
