### PR TITLE
liblcf 0.3 (new formula)

### PR DESCRIPTION
**Pull request by tomyun**
[liblcf](https://github.com/EasyRPG/liblcf) is a library required to build EasyRPG Player.

### CODE REVIEW

**Comment by mistydemeo** [comment]
Is it feasible to write a test for this, or would it be hard to find open-licensed test data?

**Comment by tomyun** [comment]
Thanks to EasyRPG/liblcf#147, the formula is updated with some tests.

- `test` block with `ToUnixTimestamp()`.
- `make check` call added.

By the way, `pkg-config --cflags liblcf` does not run correctly due to keg-only `icu4c` and `expat` dependency. Any suggestion on dealing with such a case?

**Comment by fdelapena** [comment]
On our documented setup we use [PKG_CONFIG_PATH to see icu4c and expat](https://easy-rpg.org/wiki/development/compiling/liblcf/osx/autotools), but I don't know if exists a better way or convention with Homebrew.

**Comment by mistydemeo** [comment]
@BrewTestBot test this please

**Comment by mistydemeo** [comment]
Thanks very much!

**Pull request closed without merging**
