### PR TITLE
cataclysm: save user generated data in home dir

### PR DESCRIPTION
**Pull request by ddunwoody**
This is a straight update of #663  in response to comments; I don't wish to take credit for @sharpner's work.

### CODE REVIEW

**Comment by sharpner** [comment]
I'm glad you did this, thank you! :)

**Comment by zanderzhng** [comment]
@BrewTestBot maybe test first?

**Comment by tomyun** [comment]
@zanderzhng it's already passed the test, but it probably needs rebase once #731 gets merged. Let's do that first.

**Comment by apjanke** [comment]
Along with the rebase, this should probably get a `revision` bump since it changes the installed binaries and their behavior.

**Comment by ddunwoody** [comment]
I've messed up and pushed the wrong branch to this when rebasing!  Stand by...

**Pull request closed without merging**
