### PR TITLE
xshogi 1.4.2 (new formula)

### PR DESCRIPTION
**Pull request by tomyun**
XShogi is now [separated](http://savannah.gnu.org/forum/forum.php?forum_id=7884) from GNU Shogi (#308).

No `test` block. Usual `xshogi -h` trick somehow didn't work.

### CODE REVIEW

**Comment by mistydemeo** [comment]
```

Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/xshogi
Target /usr/local/bin/xshogi
is a symlink belonging to gnu-shogi. You can unlink it:
  brew unlink gnu-shogi

To force the link and overwrite all conflicting files:
  brew link --overwrite xshogi

To list all files that would be deleted:
  brew link --overwrite --dry-run xshogi

Possible conflicting files are:
/usr/local/bin/xshogi -> /usr/local/Cellar/gnu-shogi/1.3.2/bin/xshogi
/usr/local/share/man/man6/xshogi.6 -> /usr/local/Cellar/gnu-shogi/1.3.2/share/man/man6/xshogi.6
```

Looks like gnu-shogi might be installing files by the same names?

**Comment by mistydemeo** [comment]
@BrewTestBot test this please

**Comment by tomyun** [comment]
`gnu-shogi` used to install `xshogi` together and the bot likely ran with an old dependency. Now the bot seems to only complain about missing `test` block.

**Comment by mistydemeo** [comment]
Thanks! Merged.

**Pull request closed without merging**
