### PR TITLE
supertux: Re-add patch

### PR DESCRIPTION
**Pull request by equal-l2**
The patch was supposed to be included in the latest release.

### CODE REVIEW

**Comment by equal-l2** [comment]
Also some tweaks added.

**Comment by mistydemeo** [comment]
Should we add a revision to make sure that anyone who got the version without the patch gets this version bump?

**Comment by equal-l2** [comment]
@mistydemeo 

> Should we add a revision

You're right.
I've added revision now.

**Comment by mistydemeo** [comment]
Thanks!

**Pull request closed without merging**
