### PR TITLE
A formula for the terminal Space Invaders clone posted today on HN.

### PR DESCRIPTION
**Pull request by tduzan**
HN article: https://news.ycombinator.com/item?id=10078928
Written in Golang, this is a completely ASCII art implementation of
Space Invaders which works in the terminal.  Compatible with any POSIX
compliant system that can run Go.

### CODE REVIEW

**Comment by tduzan** [comment]
Not sure if this will pass your automated testing.  There's no test loop in the formula because the application being built/installed does not provide any non-interactive way to invoke it.  It's a shell-based game which can only be invoked interactively at the terminal.

**Comment by dunn** [comment]
You might be able to get a primitive test going using `IO.popen`.  Take a look at the datomic formula (https://github.com/Homebrew/homebrew/blob/master/Library/Formula/datomic.rb#L30) or grep around for other examples.

**Comment by tduzan** [comment]
Thanks @dunn, I'll see if I can make that work.  Stand-by for an update to this PR.

**Comment by tduzan** [comment]
I am not a Ruby programmer by any stretch, so maybe I misunderstand the pipe facility for Ruby, but I get the following stacktrace when attempting a test using IO.popen where I do pipe.puts "q", since "q" quits the application.  I have to manually enter "q" after I run the test, as it never pipes it through...

```
❯ brew test spaceinvaders
Testing homebrew/games/spaceinvaders
Error: homebrew/games/spaceinvaders: failed
not opened for writing
/usr/local/Library/Taps/homebrew/homebrew-games/spaceinvaders.rb:35:in `write'
/usr/local/Library/Taps/homebrew/homebrew-games/spaceinvaders.rb:35:in `puts'
/usr/local/Library/Taps/homebrew/homebrew-games/spaceinvaders.rb:35:in `block (2 levels) in <class:Spaceinvaders>'
/usr/local/Library/Taps/homebrew/homebrew-games/spaceinvaders.rb:34:in `popen'
/usr/local/Library/Taps/homebrew/homebrew-games/spaceinvaders.rb:34:in `block in <class:Spaceinvaders>'
/usr/local/Library/Homebrew/formula.rb:951:in `block in run_test'
/usr/local/Library/Homebrew/extend/fileutils.rb:16:in `mktemp'
/usr/local/Library/Homebrew/formula.rb:947:in `run_test'
/usr/local/Library/Homebrew/test.rb:28:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/usr/local/Library/Homebrew/test.rb:27:in `<main>'
```

Here's the test:

```ruby
  test do
    IO.popen("#{bin}/spaceinvaders") do |pipe|
      pipe.puts "q"
      pipe.close_write
      pipe.close
    end
  end
```

**Comment by tduzan** [comment]
I fixed the pipe where it was previously read-only which is what resulted in the stack trace.  I dug through the Go code of the underlying software and it's just checking for a character event from nsf-termbox (which it imports), which is mapped to a rune.  A rune in Go is a Unicode (UTF-8) character.  So the pipe writing a "q" should be enough to trigger the application to quit, but it does not.  Manually hitting "q" results in it quitting without a stacktrace now in the unit test, and reports the test successful, but it does not quit automatically.

I'm at a loss on what could resolve this.  Among other changes, I just updated the formula to release v1.1 from the spaceinvaders Git repo.  Any thoughts @dunn on what I can do going from here?  @asib is the original author of the spaceinvaders game, perhaps he has some ideas as well.

Thanks all for your patience with me, this is my first attempt at writing a formula for Homebrew.

**Comment by dunn** [comment]
I'm seeing the same behavior, but it's passing on the bot so I think it's OK.

**Comment by dunn** [comment]
I do wonder, though, if the name of the formula should be tweaked.  It's not THE Space Invaders; maybe `space-invaders-go` would be more appropriate.  @mistydemeo can override me here, though.

**Comment by tduzan** [comment]
Thanks for the update @dunn.  Sorry I didn't respond sooner.  Can we go ahead and merge this since the bot test passed then?  If you think a rename is necessary that's a quick fix, just let me know.

**Comment by tduzan** [comment]
Also, not sure what the project policy is, but if you'd like I can rebase my changes to a single commit since we have a passing test now.

**Comment by dunn** [comment]
Yeah, could you rename it, and squash it down to a single commit? Thanks so much!

**Comment by tduzan** [comment]
It's been renamed to spaceinvaders-go and squashed to a single commit.  Please let me know if I need to make any other modifications for acceptance.  Thanks @dunn

**Comment by tduzan** [comment]
Actually, hold on merging.  Looks like a few days ago he released version 1.2.  Let me update the formula to the latest version of upstream and re-verify before we merge.  Might as well get it in one go.  I will layer the v1.2 update on top of the rebase, since those should remain in history as two separate commits.

Thanks.

**Comment by tduzan** [comment]
It's been updated to v1.2.  Had to update it's Go build-deps, including adding a new dependency upstream added for joystick support.  Looks like the testbot might be failing now on this however, although I haven't changed anything about the test parameters and the behavior when manually running "brew test" remains the same.

**Comment by dunn** [comment]
Looks like a bot hiccup. I queued it up again.

**Comment by tduzan** [comment]
Looks like it worked after you queued the bot again.  Is this now acceptable to merge or do I need to make any other changes?  Thanks.

**Comment by dunn** [comment]
Looks good, thank you for contributing! Merged in bfa5e172c6bdbcb85a30e860b67e2b0360d77ea0.

**Pull request closed without merging**
