### PR TITLE
Mednafen 0.9.38.5

### PR DESCRIPTION
**Pull request by yisraeldov**
updated to 0.9.38

Fixes some issues like netplay on PS1

Needs to use coreutills and builtin gcc or the complied app will throw test errors.

### CODE REVIEW

**Comment by dunn** [comment]
Failing to build on Mountain Lion:
```
../../include/mednafen/types.h:20:10: fatal error: 'type_traits' file not found
#include <type_traits>
         ^
1 error generated.
```
See http://bot.brew.sh/job/Homebrew%20Games%20Pull%20Requests/354/version=mountain_lion/testReport/junit/brew-test-bot/mountain_lion/install_Homebrew_games_mednafen/

Then various audit warnings:
```
        Error: 8 problems in 1 formula
homebrew/games/mednafen:
 * 21: Trailing whitespace was found
 * Use "#{ENV.cc}" instead of hard-coding "gcc"
 * Use "#{ENV.cc}" instead of hard-coding "gcc"
 * Use "#{ENV.cxx}" instead of hard-coding "g++"
 * Use "#{ENV.cxx}" instead of hard-coding "g++"
 * 30: Trailing whitespace was found
 * 32: Trailing whitespace was found
 * Use spaces instead of tabs for indentation
```

**Comment by tomyun** [comment]
Just out of curiosity, can `fails_with :clang` still force using GCC on recent OSes no longer bundled with GCC? If so, it'd be nice to help building `mednafen`, since I was also long waiting for `clang` fix on [this particular issue](http://llvm.org/bugs/show_bug.cgi?id=15470), but saw it's not going to happen anytime soon.

**Comment by yisraeldov** [comment]
require GCC and build it

**Comment by mistydemeo** [comment]
Merged the newer mednafen; thanks!

**Pull request closed without merging**
