### PR TITLE
New Formula: guichan 0.8.2

### PR DESCRIPTION
**Pull request by s172262**

### CODE REVIEW

**Comment by dunn** [comment]
Can you add a test? Just something to test basic functionality.  Thanks!

**Comment by s172262** [comment]
I close this PR.
I tried the example code in source package. But those failed at loading images.

**Comment by s172262** [comment]
Guichan is not guilty! Guichan works now! The source of all evil is broken SDL_image (https://github.com/Homebrew/homebrew-core/pull/281)

**Comment by apjanke** [comment]
@BrewTestBot test this please

**Comment by apjanke** [comment]
Merged. Thank you for your contribution to Homebrew!

**Pull request closed without merging**
