### PR TITLE
advancemame 3.2

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by mistydemeo** [comment]
Fails while linking:

> ld: internal error: atom not found in symbolIndex(__ZNSt3__119__tree_right_rotateIPNS_16__tree_node_baseIPvEEEEvT_) for architecture x86_64

**Comment by mistydemeo** [comment]
Same failure. :/

**Comment by ilovezfs** [comment]
Not surprised, unfortunately.

**Comment by mistydemeo** [comment]
Maybe we should just pull it without a Yosemite bottle?

**Comment by ilovezfs** [comment]
@mistydemeo the difference was `LDFLAGS=#{ENV.ldflags}` hehe

**Pull request closed without merging**
