### PR TITLE
Updated Yetris homepage

### PR DESCRIPTION
**Pull request by trenton42**
Old homepage no longer seems to be active, pointed to github project page instead.

### CODE REVIEW

**Comment by mistydemeo** [comment]
Thanks!

**Comment by trenton42** [comment]
Hey @mistydemeo, did I need to do something else with this? I noticed it was closed but not merged. Thanks!

**Comment by mistydemeo** [comment]
It was merged in 3f88f821b82ead6e03c667dc6522bf219d4d5458!

**Comment by trenton42** [comment]
Oops! I missed that! Thanks!

**Pull request closed without merging**
