### PR TITLE
mame 0.177

### PR DESCRIPTION
**Pull request by tomyun**
- Regular monthly release
- Build documents with `sphinx-doc` (no longer distributed in `docs` directory -- mamedev/mame@a86a53fb64dd4b9e6dfa3d6a1ebd48e30f9d3efa)
- Remove GLSL `shader` installation in favor of new `bgfx`
- Add `ini` and `uismall.bdf` to `pkgshare`

### CODE REVIEW

**Comment by dunn** [comment]
Some failures at the bottom of https://bot.brew.sh/job/Homebrew%20Games%20Pull%20Requests/963/version=mavericks/testReport/brew-test-bot/mavericks/install_homebrew_games_mame/
```
Compiling src/mame/drivers/atarisy4.cpp...
In file included from ../../../../../src/mame/drivers/atarisy4.cpp:22:
../../../../../src/devices/video/poly.h:227:32: error: non-type template argument is not a constant expression
        typedef poly_array<work_unit, std::min(_MaxPolys * UNITS_PER_POLY, 65535)> unit_array;
                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../../../src/mame/drivers/atarisy4.cpp:33:34: note: in instantiation of template class 'poly_manager<float, atarisy4_polydata, 2, 8192>' requested here
class atarisy4_renderer : public poly_manager<float, atarisy4_polydata, 2, 8192>
                                 ^
In file included from ../../../../../src/mame/drivers/atarisy4.cpp:22:
../../../../../src/devices/video/poly.h:227:32: note: non-constexpr function 'min<int>' cannot be used in a constant expression
        typedef poly_array<work_unit, std::min(_MaxPolys * UNITS_PER_POLY, 65535)> unit_array;
                                      ^
In file included from ../../../../../src/mame/drivers/atarisy4.cpp:1:
In file included from /private/tmp/mame-20160901-15718-1kfewch/mame-mame0177/build/projects/sdl/mame/gmake-osx-clang/../../../../../src/emu/emu.h:21:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/list:178:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:2544:1: note: declared here
min(const _Tp& __a, const _Tp& __b)
^
../../../../../src/mame/drivers/atarisy4.cpp:39:43: error: unknown type name 'extent_t'; did you mean 'poly_manager<float, atarisy4_polydata, 2, 8192>::extent_t'?
        void draw_scanline(INT32 scanline, const extent_t &extent, const atarisy4_polydata &extradata, int threadid);
                                                 ^~~~~~~~
                                                 poly_manager<float, atarisy4_polydata, 2, 8192>::extent_t
In file included from ../../../../../src/mame/drivers/atarisy4.cpp:22:
../../../../../src/devices/video/poly.h:111:9: note: 'poly_manager<float, atarisy4_polydata, 2, 8192>::extent_t' declared here
        struct extent_t
               ^
../../../../../src/mame/drivers/atarisy4.cpp:177:4: error: type 'poly_manager<float, atarisy4_polydata, 2, 8192>' is not a direct or virtual base of 'atarisy4_renderer'
        : poly_manager<float, atarisy4_polydata, 2, 8192>(screen, POLYFLAG_NO_WORK_QUEUE),
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../../../src/mame/drivers/atarisy4.cpp:281:61: error: unknown type name 'extent_t'; did you mean 'poly_manager<float, atarisy4_polydata, 2, 8192>::extent_t'?
void atarisy4_renderer::draw_scanline(INT32 scanline, const extent_t &extent, const atarisy4_polydata &extradata, int threadid)
                                                            ^~~~~~~~
                                                            poly_manager<float, atarisy4_polydata, 2, 8192>::extent_t
In file included from ../../../../../src/mame/drivers/atarisy4.cpp:22:
../../../../../src/devices/video/poly.h:111:9: note: 'poly_manager<float, atarisy4_polydata, 2, 8192>::extent_t' declared here
        struct extent_t
               ^
../../../../../src/mame/drivers/atarisy4.cpp:303:2: error: unknown type name 'vertex_t'; did you mean 'poly_manager<float, atarisy4_polydata, 2, 8192>::vertex_t'?
        vertex_t v1, v2, v3;
        ^~~~~~~~
        poly_manager<float, atarisy4_polydata, 2, 8192>::vertex_t
In file included from ../../../../../src/mame/drivers/atarisy4.cpp:22:
../../../../../src/devices/video/poly.h:101:9: note: 'poly_manager<float, atarisy4_polydata, 2, 8192>::vertex_t' declared here
        struct vertex_t
               ^
../../../../../src/mame/drivers/atarisy4.cpp:304:33: error: use of undeclared identifier 'object_data_alloc'; did you mean 'poly_manager<float, atarisy4_polydata, 2, 8192>::object_data_alloc'?
        atarisy4_polydata &extradata = object_data_alloc();
                                       ^~~~~~~~~~~~~~~~~
                                       poly_manager<float, atarisy4_polydata, 2, 8192>::object_data_alloc
In file included from ../../../../../src/mame/drivers/atarisy4.cpp:22:
../../../../../src/devices/video/poly.h:138:15: note: 'poly_manager<float, atarisy4_polydata, 2, 8192>::object_data_alloc' declared here
        _ObjectData &object_data_alloc();
                     ^
../../../../../src/mame/drivers/atarisy4.cpp:304:33: error: call to non-static member function without an object argument
        atarisy4_polydata &extradata = object_data_alloc();
                                       ^~~~~~~~~~~~~~~~~
../../../../../src/mame/drivers/atarisy4.cpp:305:2: error: unknown type name 'render_delegate'; did you mean 'poly_manager<float, atarisy4_polydata, 2, 8192>::render_delegate'?
        render_delegate rd_scan = render_delegate(FUNC(atarisy4_renderer::draw_scanline), this);
        ^~~~~~~~~~~~~~~
        poly_manager<float, atarisy4_polydata, 2, 8192>::render_delegate
In file included from ../../../../../src/mame/drivers/atarisy4.cpp:22:
../../../../../src/devices/video/poly.h:123:77: note: 'poly_manager<float, atarisy4_polydata, 2, 8192>::render_delegate' declared here
        typedef delegate<void (INT32, const extent_t &, const _ObjectData &, int)> render_delegate;
                                                                                   ^
../../../../../src/mame/drivers/atarisy4.cpp:305:28: error: use of undeclared identifier 'render_delegate'
        render_delegate rd_scan = render_delegate(FUNC(atarisy4_renderer::draw_scanline), this);
                                  ^
../../../../../src/mame/drivers/atarisy4.cpp:324:3: error: use of undeclared identifier 'render_triangle'; did you mean 'poly_manager<float, atarisy4_polydata, 2, 8192>::render_triangle'?
                render_triangle(clip, rd_scan, 1, v1, v2, v3);
                ^~~~~~~~~~~~~~~
                poly_manager<float, atarisy4_polydata, 2, 8192>::render_triangle
In file included from ../../../../../src/mame/drivers/atarisy4.cpp:22:
../../../../../src/devices/video/poly.h:145:9: note: 'poly_manager<float, atarisy4_polydata, 2, 8192>::render_triangle' declared here
        UINT32 render_triangle(const rectangle &cliprect, render_delegate callback, int paramcount, const vertex_t &v1, const vertex_t &v2, const vertex_t &v3);
               ^
../../../../../src/mame/drivers/atarisy4.cpp:324:3: error: call to non-static member function without an object argument
                render_triangle(clip, rd_scan, 1, v1, v2, v3);
                ^~~~~~~~~~~~~~~
../../../../../src/mame/drivers/atarisy4.cpp:473:16: error: no member named 'wait' in 'atarisy4_renderer'
                        m_renderer->wait();
                        ~~~~~~~~~~  ^
12 errors generated.
make[2]: *** [../../../../osx_clang/obj/x64/Release/src/mame/drivers/atarisy4.o] Error 1

**Comment by tomyun** [comment]
Given that it only happens with Mavericks, I feel like it has something to with the dev's recent adoption of more C++11 and C++14 features in the code.

By the way, just tried `fails_with :clang` block to force gcc compilation, but still failed with another error:

```
Compiling src/osd/modules/render/drawbgfx.cpp...
In file included from ../../../../../src/osd/modules/render/drawbgfx.cpp:16:0:
/usr/local/include/SDL2/SDL_syswm.h:218:65: error: missing binary operator before token "("
 #if defined(__OBJC__) && defined(__has_feature) && __has_feature(objc_arc)
```

Guess it's time to use `depends_on :macos => :yosemite`?

**Comment by tomyun** [comment]
Hmm, it seems to be related with `std::min` not being `constexpr` in C++11. It **is** `constexpr` in C++14 that probably makes Yosemite and El Capitan happy.

mamedev/mame#1189 was trying to patch this issue for GCC4 on Linux, but not accepted upstream.

**Comment by dunn** [comment]
> Guess it's time to use depends_on :macos => :yosemite? 

Fine with me, if you don't think upstream is willing to support Mavericks.

**Comment by tomyun** [comment]
Just added the patch above and it seems to build fine on Mavericks. Maybe we could consider dropping Mavericks support after Sierra gets released. There would be no build bot available for it anyways.

**Comment by dunn** [comment]
If the patch wasn't accepted upstream, let's just drop Mavericks now.

**Comment by tomyun** [comment]
Okay. Then would you also want to drop other stuffs we added for Snow Leopard and Linux? They will become no more relevant once we add strict dependency on Yosemite and above.

- Python dependency for Snow Leopard (`depends_on :python`)
- Explicit configuration for 32 bit machines (`PTR64`)
- Prevent building with GCC4 (`fails_with`)

**Comment by dunn** [comment]
Adding a minimum macOS requirement doesn't imply a non-Linux requirement, so you can leave in the Linux stuff.

**Comment by tomyun** [comment]
Formula updated:

- Remove Python dependency for Snow Leopard
- Remove explicit configuration for 32 bit machines
- Add requirement for Yosemite or above

**Comment by dunn** [comment]
Great! Merged as ee747b1b3f138ece0ec7bbdef0e25a2b9c4ddc51.

**Pull request closed without merging**
