### PR TITLE
supertux 0.5.1

### PR DESCRIPTION
**Pull request by equal-l2**

### CODE REVIEW

**Comment by mistydemeo** [comment]
Thanks!

**Comment by tomyun** [comment]
The game doesn't seem to run correctly, at least on my machine:

```
$ supertux2
[WARNING] /tmp/supertux-20161227-35285-7dwq56/SuperTux-v0.5.1-Source/src/supertux/main.cpp:188 Couldn't add '/usr/local/share/supertux' to physfs searchpath: unsupported
[FATAL] /tmp/supertux-20161227-35285-7dwq56/SuperTux-v0.5.1-Source/src/supertux/main.cpp:510 Unexpected exception: Couldn't open 'images/engine/icons/supertux-256x256.png': not found
```

I thought this issue was fixed by a patch from SuperTux/supertux#614 when we added 0.5.0 (#681), but somehow reappears with the new release. Does it work for you all?

**Comment by equal-l2** [comment]
@tomyun 
Not work on my Mac, too.
Fix for #681 is certainly in the release.

Maybe fix by upstream is needed.

**Comment by equal-l2** [comment]
@mistydemeo
Could you revert this version bump, as a workaround?

I'll make another PR for this version bump.

**Comment by equal-l2** [comment]
Re-added patch.
#767

**Pull request closed without merging**
