### PR TITLE
cockatrice 2016-12-31

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by mistydemeo** [comment]
Failing to find the `macx-clang` spec:

```
CMake Error at /usr/local/lib/cmake/Qt5Core/Qt5CoreConfig.cmake:15 (message):
  The imported target "Qt5::Core" references the file

     "/usr/local/.//mkspecs/macx-clang"

  but this file does not exist.
```

We don't symlink the `mkspecs` directory into `/usr/local`.

**Comment by ilovezfs** [comment]
This should be fixed now that we've made qt5 keg only again.

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
:rocket:

**Pull request closed without merging**
