### PR TITLE
vecx 1.1

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
```
clang -O3 -Wall -Wextra -I/usr/local/include/SDL -D_GNU_SOURCE=1 -D_THREAD_SAFE   -c -o vecx.o vecx.c
osint.c:3:10: fatal error: 'SDL_image.h' file not found
#include "SDL_image.h"
         ^
1 error generated.
make: *** [osint.o] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by tomyun** [comment]
You may just need to add `depends_on "sdl_image"`. `head` already does that.

**Comment by apjanke** [comment]
Yeah, adding `depends_on "sdl_image"` fixes it for me. I put in a PR for that and a couple other changes at #716.

**Comment by ilovezfs** [comment]
@apjanke in the future if you do that, please close my PR even if you haven't even opened yours yet. Thanks!

**Comment by apjanke** [comment]
Will do. Sorry!

**Pull request closed without merging**
