### PR TITLE
fizmo 0.7.9 (new formula)

### PR DESCRIPTION
**Pull request by tomyun**
[Fizmo](https://christoph-ender.de/fizmo/) is a [Z-Machine](https://en.wikipedia.org/wiki/Z-machine) interpreter.

- ~~requires `homebrew/dupes/ncurses` due to its dependency on `ncursesw`~~
- use system `ncurses` as `ncursesw` (Homebrew/homebrew#32947, Homebrew/homebrew#38355)

### CODE REVIEW

**Comment by dunn** [comment]
Non-zero exit status for `fizmo-ncursesw --help`:
```
==> /usr/local/Cellar/fizmo/0.7.9/bin/fizmo-console --help
==> /usr/local/Cellar/fizmo/0.7.9/bin/fizmo-ncursesw --help
Error: homebrew/games/fizmo: failed
<0> expected but was
<255>.

**Comment by tomyun** [comment]
Hmm.. It works fine locally and even the bottle downloaded from the server works fine with me. Any idea on such a case?

**Comment by dunn** [comment]
I suppose it's possible it's trying to do something that's prevented by the sandbox, though I'm not sure what.  Does `brew test -v --sandbox fizmo` work locally?

**Comment by tomyun** [comment]
Yes, `--sandbox` also works for me locally.

**Pull request closed without merging**
