### PR TITLE
Add several usability patches to nethack

### PR DESCRIPTION
**Pull request by ffleming**
Nethack.alt.org is widely seen as running the best version of Nethack around, but high latency impacts the experience.  This commit alters the version of nethack used by homebrew-games to incorporate the patches used by nethack.alt.org including
* [Menucolors](http://bilious.alt.org/?11)
* [Statuscolors](http://bilious.alt.org/?142)
* [Sortloot](http://bilious.alt.org/?42)
* Over 20 bugfixes
* And quite a few more (see [my fork of NAO's nethack](https://github.com/ffleming/nethack-3.4.3-nao-osx/blob/v1.0/README.md) for more information)

This version also compiles in a a few options that are available but disabled on a standard Nethack install:
* `DLB` for a cleaner install (ie there are fewer files hanging out in `/path/to/cellar/libexec`),
* `SHELL` so that a player can type `!` to drop to a shell
* `AUTOPICKUP_EXCEPTIONS` to make autopickup more configurable via `.nethackrc`

### CODE REVIEW

**Comment by mistydemeo** [comment]
Ping.

**Comment by mistydemeo** [comment]
This still needs a `revision 1` line under the version number too, please!

**Comment by ffleming** [comment]
I've hit a snag that I've been unable to resolve, and I think I'm finally giving up on it: this patch is not compatible with saves from the current nethack version, so anyone upgrading would be unable to continue old games.  I'd hoped that I could figure something out, but no such luck.  What do you advise on that?  I won't have my feelings hurt if it sinks the project, though of course I hope that there's some other solution!

**Comment by bfontaine** [comment]
Any update here?

**Comment by xu-cheng** [comment]
This PR need a rebase.

**Comment by ffleming** [comment]
I've added the revision and rebased; I'm not sure why Jenkins is failing.  I'm looking into it now, but any advice is much appreciated!

**Comment by mistydemeo** [comment]
@BrewTestBot test this please

**Comment by ffleming** [comment]
Thanks, Misty! I'm switching to SHA256 right now, and will see what I can do with the Mountain Lion postinstall/`make manpages` error.

**Comment by mistydemeo** [comment]
@BrewTestBot test this please

**Comment by ffleming** [comment]
Hot dog! :confetti_ball: :dog: :confetti_ball:

**Comment by dunn** [comment]
Should we add a caveat about the non-compatibility of save files?

**Comment by ffleming** [comment]
Ahh, absolutely @dunn.  Added!

**Comment by dunn** [comment]
Does the release of 3.6.0 affect this PR?

**Comment by mistydemeo** [comment]
Some of these patches were incorporated into Nethack 3.6.0 proper, including:

```
menucolors
pickup thrown
statue glyphs
dungeon overview
sortloot
```

**Comment by dunn** [comment]
Should we merge #461 first, or try to tackle this in one?

**Comment by mistydemeo** [comment]
Are any of the patches that broke savefile compatibility the ones that were incorporated into Nethack 3.6.0?

**Comment by mistydemeo** [comment]
If not, we could merge that first and then incorporate additional patches later.

**Comment by jthemphill** [comment]
3.6.0 is not savefile compatible with 3.4.3 =/

> Given the rather fundamental changes in this release as noted above, old save and bones files understandably will not be compatible with version 3.6.

http://nethack.org/v360/release.html

**Comment by mistydemeo** [comment]
Yeah, so savefile compat is breaking either way. It's possible we might want to integrate additional patches from here, but I'm not sure if the other patches proposed in this PR will break saves a second time.

**Comment by mistydemeo** [comment]
Closing due to the new nethack, but would review patches for the current version - and actually act in a timely manner this time! Sorry again.

**Pull request closed without merging**
