### PR TITLE
Update minetest to 0.4.12

### PR DESCRIPTION
**Pull request by neoascetic**

### CODE REVIEW

**Comment by neoascetic** [comment]
I have no idea why build is broken, I think something wrong with server setup. @mistydemeo could you take a look please?

**Comment by mistydemeo** [comment]
The Mavericks bot is currently down - sorry for the inconvenience. I'll get them to retest once it's back in order.

**Comment by jacknagel** [comment]
@BrewTestBot test this please

**Comment by neoascetic** [comment]
@mistydemeo may we have this merged?

**Comment by mistydemeo** [comment]
Looks like the bot didn't upload the binaries; trying again.

**Comment by mistydemeo** [comment]
@BrewTestBot test this please

**Comment by MrMormon** [comment]
Is BrewTestBot supposed to update the binaries' sha1 sums too?

**Comment by mistydemeo** [comment]
Yep, it generates a new commit to do that!

**Comment by mistydemeo** [comment]
Merged, thanks!

**Comment by neoascetic** [comment]
Just noticed that homebrew have moved from SourceForge to Bintray for bottles hosting. That's great, no more annoying SF errors.
Thank you.

**Comment by MrMormon** [comment]
Yeah...
==> Installing minetest
==> Downloading https://downloads.sf.net/project/machomebrew/Bottles/games/minet
Already downloaded: /Library/Caches/Homebrew/minetest-0.4.12.yosemite.bottle.tar.gz
Error: SHA1 mismatch
Expected: 761719bd9e84497fcb0a15f95efa06f2f65dde2d
Actual: f2bb3bc988d893bbcb94efa5f22c18045ed570bd
Archive: /Library/Caches/Homebrew/minetest-0.4.12.yosemite.bottle.tar.gz
To retry an incomplete download, remove the file above.
Warning: Bottle installation failed: building from source.

**Comment by mistydemeo** [comment]
Homebrew shouldn't be downloading it from Sourceforge - have you run `brew update` lately?

**Pull request closed without merging**
