### PR TITLE
Update Gearsystem to version 2.2

### PR DESCRIPTION
**Pull request by drhelius**
Updated to latest release.

### CODE REVIEW

**Comment by dunn** [comment]
Possible to add a quick test while you're at it?

**Comment by drhelius** [comment]
This is a desktop emulator, I'm afraid I don't know what to test.

**Comment by dunn** [comment]
Something like `--version` is better than nothing; are there any basic non-interactive commands?

**Comment by drhelius** [comment]
Nope, if you run it from the command line the application just opens and run in the foreground until the user closes it. I'm afraid there aren't any parameters.

**Comment by dunn** [comment]
OK, merging as-is.  Thank you for contributing!

**Pull request closed without merging**
