### PR TITLE
blastem 0.4.1

### PR DESCRIPTION
**Pull request by tomyun**
A new version just came out while waiting for #568..

### CODE REVIEW

**Comment by dunn** [comment]
Looks like it's trying to `touch` in a non-standard way: https://bot.brew.sh/job/Homebrew%20Games%20Pull%20Requests/925/version=yosemite/testReport/junit/brew-test-bot/yosemite/install_homebrew_games_blastem/

**Comment by tomyun** [comment]
`touch` issue seems to be solved by adding `ENV.deparalleize` for building `xcftools`. Now it builds fine except on El Capitan where some server-side homebrew issues are observed:

```
==> FAILED
Error: /usr/local/Library/Taps/homebrew/homebrew-core/Formula/isync.rb:9: syntax error, unexpected <<, expecting keyword_end
<<<<<<< Updated upstream
  ^
/usr/local/Library/Taps/homebrew/homebrew-core/Formula/isync.rb:14: syntax error, unexpected ===, expecting keyword_end
=======
   ^
/usr/local/Library/Taps/homebrew/homebrew-core/Formula/isync.rb:16: syntax error, unexpected >>, expecting keyword_end
>>>>>>> Stashed changes
  ^
```

**Comment by dunn** [comment]
> `touch` issue seems to be solved by adding `ENV.deparalleize` for building xcftools

We usually consider parallelization failures to be bugs; could you report this upstream? Thanks!

**Comment by tomyun** [comment]
Those issues of `xcftools`, which is just one of `resource` for building `blastem`, were already reported upstream (Homebrew/homebrew-core#1216), but I doubt if we could hear back anytime soon. `blastem` itself builds fine as is.

**Comment by dunn** [comment]
Oh, gotcha.  Merged in c522032cd3aeaa7f45451ccfce830cecee71ded1, then!

**Pull request closed without merging**
