### PR TITLE
go-gui: modernize

### PR DESCRIPTION
**Pull request by tomyun**
- formula modernized
- `head` added (with manually installed `quaqua` look & feel and `docbook` help files)
- install `gogui` script to run the app bundle
- `caveats` removed (brew already explains `linkapps`)
- `test` added

### CODE REVIEW

**Comment by dunn** [comment]
@BrewTestBot test this please

**Comment by dunn** [comment]
When I run `brew test go-gui` I get a Java pop-up with "To open “GoGui” you need to install the legacy Java SE 6 runtime."  Can you add a `depends_on :java => "1.6"` line? Thanks!

**Comment by tomyun** [comment]
`depends_on :java => "1.6"` added.

**Comment by dunn** [comment]
Thank you! Merged in 947a9aa594bf2011481aca82386f8dce5a2c3c22.

**Pull request closed without merging**
